name: Correction and Posting
on:
  push:
    branches: [master]

jobs:
  job:
    name: Correction and Posting
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get diff files
        run: |
            for file in $(git diff ${{github.event.before}}..${{github.event.after}} --name-only -- '*.md') ; do
              # ファイルの内容を環境変数に設定
              export MD_CONTENT=$(cat $file)
              # 添削と投稿
              node ./scripts/post.js
            done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WP_APPLICATION_PASSWORD: ${{ secrets.NOTION_API_KEY }}